---
title: Hoosac Institute
timezone: America/New_York
permalink: pretty
collections:
  journal:
    title: Journal
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
