---
title: Hoosac Institute
timezone: America/New_York
repository: caseyg/hoosacinstitute

permalink: pretty

theme: minima
minima:
  date_format: "%b %-d, %Y"

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
  journal:
    title: Journal
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

defaults:
  -
    scope:
      path: ""
      type: "journal"
    values:
      layout: "journal"
