---
title: Hoosac Institute
timezone: America/New_York
collections:
  journal:
    title: Journal
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
repository: caseyg/hoosacinstitute
permalink: pretty
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
